"""Change price int -> float

Revision ID: ca0306b2eb15
Revises: f0688b6b5f3f
Create Date: 2022-09-06 15:36:08.815852

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ca0306b2eb15'
down_revision = 'f0688b6b5f3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_subscriptions', 'price', existing_type=sa.Integer(), type_=sa.Float())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token_subscriptions', 'price', existing_type=sa.Float(), type_=sa.Integer())
    # ### end Alembic commands ###
