"""Create db schema

Revision ID: cf77fb02ca05
Revises: 
Create Date: 2022-08-26 12:11:59.975821

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'cf77fb02ca05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('telegram_id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.Text(), nullable=True),
        sa.Column('last_name', sa.Text(), nullable=True),
        sa.Column('username', sa.Text(), nullable=True),
        sa.Column('language_code', sa.Text(), nullable=True),
        sa.Column('is_bot', sa.Boolean(), nullable=True),
        sa.Column('is_premium', sa.Boolean(), nullable=True),
        sa.Column('disabled', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('telegram_id'),
        sa.UniqueConstraint('telegram_id')
    )
    op.create_table(
        'market_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.Integer(), nullable=True),
        sa.Column('percent', sa.Integer(), nullable=True),
        sa.Column('market_type', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_index(
        op.f('ix_market_subscriptions_telegram_id'),
        'market_subscriptions',
        ['telegram_id'],
        unique=False
    )
    op.create_table(
        'token_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.Integer(), nullable=True),
        sa.Column('symbol', sa.Text(), nullable=True),
        sa.Column('percent', sa.Integer(), nullable=True),
        sa.Column('market_type', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_index(
        op.f('ix_token_subscriptions_telegram_id'),
        'token_subscriptions',
        ['telegram_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_token_subscriptions_telegram_id'),
        table_name='token_subscriptions'
    )
    op.drop_table('token_subscriptions')
    op.drop_index(
        op.f('ix_market_subscriptions_telegram_id'),
        table_name='market_subscriptions'
    )
    op.drop_table('market_subscriptions')
    op.drop_table('users')
    # ### end Alembic commands ###
