"""Create sunday digest

Revision ID: ea936fc745de
Revises: ca0306b2eb15
Create Date: 2022-09-06 21:47:48.732046

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ea936fc745de'
down_revision = 'ca0306b2eb15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sunday_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['telegram_id'], ['users.telegram_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sunday_subscriptions_telegram_id'),
                    'sunday_subscriptions', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sunday_subscriptions_telegram_id'),
                  table_name='sunday_subscriptions')
    op.drop_table('sunday_subscriptions')
    # ### end Alembic commands ###
