"""Add price, remove percent

Revision ID: f0688b6b5f3f
Revises: cf77fb02ca05
Create Date: 2022-08-28 20:53:45.830430

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0688b6b5f3f'
down_revision = 'cf77fb02ca05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'market_subscriptions', ['id'])
    op.add_column(
        'token_subscriptions',
        sa.Column('sign', sa.Text(), nullable=True)
    )
    op.add_column(
        'token_subscriptions',
        sa.Column('price', sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(None, 'token_subscriptions', ['id'])
    op.drop_column('token_subscriptions', 'percent')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column(
        'token_subscriptions',
        sa.Column('percent', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, 'token_subscriptions', type_='unique')
    op.drop_column('token_subscriptions', 'price')
    op.drop_column('token_subscriptions', 'sign')
    op.drop_constraint(None, 'market_subscriptions', type_='unique')
    # ### end Alembic commands ###
