"""Add muted columns

Revision ID: f0a24a55a727
Revises: ea936fc745de
Create Date: 2022-09-12 20:50:50.674980

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f0a24a55a727'
down_revision = 'ea936fc745de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_subscriptions', sa.Column(
        'muted_1h_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('market_subscriptions', sa.Column(
        'muted_24h_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'sunday_subscriptions', ['id'])
    op.add_column('token_subscriptions', sa.Column(
        'muted_1h_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('token_subscriptions', sa.Column(
        'muted_24h_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_subscriptions', 'muted_24h_at')
    op.drop_column('token_subscriptions', 'muted_1h_at')
    op.drop_constraint(None, 'sunday_subscriptions', type_='unique')
    op.drop_column('market_subscriptions', 'muted_24h_at')
    op.drop_column('market_subscriptions', 'muted_1h_at')
    # ### end Alembic commands ###
